### PR TITLE
fetch read-only google calendars

### PR DESCRIPTION
**Pull request by Karry**
Right now, I cannot see calendars of my family members shared with me as read-only. I would like to make it possible. 

Not sure if this change is enough :-)

### CODE REVIEW

**Comment by pvuorela** [comment]
On quick check at least one thing missing is setting the notebook as read-only so that the user is not able to create new events on it or make modifications. Suppose that should be somewhere around GoogleCalendarSyncAdaptor::setCalendarProperties().

Did you test this yourself already?

**Comment by Karry** [comment]
> Did you test this yourself already?

Not yet :-) It is late-nigh proposal, installation failed on the first attempt. But I will continue to work on that...

**Comment by Karry** [comment]
It is working finally :-)

**Review by pvuorela — APPROVED** [review]
Nice. Getting new calendar synced here. Some more annoying ones now too, but those can be disabled.

**Pull request merged**
